=== FrankCf08/Queen-Mary-University-of-London/Third Year/Semi-structured Dta and Advanced Data Modelling/Coursework 2/Mario (original)/mario/marioXML/mariokart.dtd
<!ENTITY % stats "(name,speed,accel,weight,handling,traction,M-turbo)">
<!ENTITY % terrain "(land,anti-g,water,air)">

<!ELEMENT name (#PCDATA)>
<!ELEMENT speed %terrain;>
<!ELEMENT accel (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT handling %terrain;>
<!ELEMENT traction (#PCDATA)>
<!ELEMENT M-turbo (#PCDATA)>

<!ELEMENT land (#PCDATA)>
<!ELEMENT anti-g (#PCDATA)>
<!ELEMENT water (#PCDATA)>
<!ELEMENT air (#PCDATA)>

<!ELEMENT MARIOKART (characters,bodies, gliders,tires)>
<!ATTLIST MARIOKART type CDATA #IMPLIED>

<!ELEMENT characters (character+)>
<!ATTLIST characters type CDATA #IMPLIED>
<!ELEMENT character %stats;>
<!ATTLIST character type CDATA #IMPLIED>

<!ELEMENT bodies (body+)>
<!ATTLIST bodies type CDATA #IMPLIED>
<!ELEMENT body %stats;>
<!ATTLIST body type CDATA #IMPLIED>

<!ELEMENT gliders (glider+)>
<!ATTLIST gliders type CDATA #IMPLIED>
<!ELEMENT glider %stats;>
<!ATTLIST glider type CDATA #IMPLIED>

<!ELEMENT tires (tire+)>
<!ATTLIST tires type CDATA #IMPLIED>
<!ELEMENT tire %stats;>
<!ATTLIST tire type CDATA #IMPLIED>

=== FrankCf08/Queen-Mary-University-of-London/Third Year/Semi-structured Dta and Advanced Data Modelling/Coursework 2/Mario (original)/mario/marioXML/copyMarioKart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MARIOKART SYSTEM "mariokart.dtd">
<?xml-stylesheet type="text/xsl" href="names.xsl"?>

<MARIOKART>
    <characters>
        <character>
            <name>Baby Peach</name>
            <speed>
                <land>2.25</land>
                <anti-g>2</anti-g>
                <water>2.5</water>
                <air>2.75</air>
            </speed>
            <accel>4</accel>
            <weight>2</weight>
            <handling>
                <land>5</land>
                <anti-g>5</anti-g>
                <water>4.5</water>
                <air>5</air>
            </handling>
            <traction>4.25</traction>
            <M-turbo>4</M-turbo>
        </character>
        <character>
            <name>Baby Rosalina</name>
            <speed>
                <land>2.25</land>
                <anti-g>2</anti-g>
                <water>2.5</water>
                <air>2.75</air>
            </speed>
            <accel>4.25</accel>
            <weight>2</weight>
            <handling>
                <land>4.75</land>
                <anti-g>4.75</anti-g>
                <water>4.25</water>
                <air>4.75</air>
            </handling>
            <traction>3.75</traction>
            <M-turbo>4</M-turbo>
        </character>
        <character>
            <name>Baby Mario</name>
            <speed>
                <land>2.5</land>
                <anti-g>2.25</anti-g>
                <water>2.75</water>
                <air>3</air>
            </speed>
            <accel>4.25</accel>
            <weight>2.25</weight>
            <handling>
                <land>4.5</land>
                <anti-g>4.5</anti-g>
                <water>4</water>
                <air>4.5</air>
            </handling>
            <traction>4</traction>
            <M-turbo>3.75</M-turbo>
        </character>
        <character>
            <name>Toadette</name>
            <speed>
                <land>2.75</land>
                <anti-g>2.5</anti-g>
                <water>3</water>
                <air>3.25</air>
            </speed>
            <accel>4.25</accel>
            <weight>2.5</weight>
            <handling>
                <land>4.25</land>
                <anti-g>4.25</anti-g>
                <water>3.75</water>
                <air>4.25</air>
            </handling>
            <traction>3.5</traction>
            <M-turbo>3.75</M-turbo>
        </character>
        <character>
            <name>Koopa Troopa</name>
            <speed>
                <land>2.75</land>
                <anti-g>2.5</anti-g>
                <water>3</water>
                <air>3.25</air>
            </speed>
            <accel>4</accel>
            <weight>2.5</weight>
            <handling>
                <land>4.5</land>
                <anti-g>4.5</anti-g>
                <water>4</water>
                <air>4.5</air>
            </handling>
            <traction>4.25</traction>
            <M-turbo>3.75</M-turbo>
        </character>
        <character>
            <name>Toad</name>
            <speed>
                <land>3</land>
                <anti-g>2.75</anti-g>
                <water>3.25</water>
                <air>3.5</air>
            </speed>
            <accel>4</accel>
            <weight>2.75</weight>
            <handling>
                <land>4.25</land>
                <anti-g>4.25</anti-g>
                <water>3.75</water>
                <air>4.25</air>
            </handling>
            <traction>4</traction>
            <M-turbo>3.5</M-turbo>
        </character>
        <character>
            <name>Cat Peach</name>
            <speed>
                <land>3.25</land>
                <anti-g>3</anti-g>
                <water>3.5</water>
                <air>3.75</air>
            </speed>
            <accel>4</accel>
            <weight>2.75</weight>
            <handling>
                <land>4</land>
                <anti-g>4</anti-g>
                <water>3.5</water>
                <air>4</air>
            </handling>
            <traction>3.75</traction>
            <M-turbo>3.5</M-turbo>
        </character>
        <character>
            <name>Peach</name>
            <speed>
                <land>3.5</land>
                <anti-g>3.25</anti-g>
                <water>3.75</water>
                <air>4</air>
            </speed>
            <accel>3.75</accel>
            <weight>3</weight>
            <handling>
                <land>3.75</land>
                <anti-g>3.75</anti-g>
                <water>3.25</water>
                <air>3.75</air>
            </handling>
            <traction>3.75</traction>
            <M-turbo>3.5</M-turbo>
        </character>
        <character>
            <name>Tanooki Mario</name>
            <speed>
                <land>3.5</land>
                <anti-g>3.25</anti-g>
                <water>3.75</water>
                <air>4</air>
            </speed>
            <accel>3.75</accel>
            <weight>3.25</weight>
            <handling>
                <land>3.75</land>
                <anti-g>3.75</anti-g>
                <water>3.25</water>
                <air>3.75</air>
            </handling>
            <traction>3.25</traction>
            <M-turbo>3.5</M-turbo>
        </character>
        <character>
            <name>Mario</name>
            <speed>
                <land>3.75</land>
                <anti-g>3.5</anti-g>
                <water>4</water>
                <air>4.25</air>
            </speed>
            <accel>3.5</accel>
            <weight>3.5</weight>
            <handling>
                <land>3.5</land>
                <anti-g>3.5</anti-g>
                <water>3</water>
                <air>3.5</air>
            </handling>
            <traction>3.5</traction>
            <M-turbo>3.25</M-turbo>
        </character>
        <character>
            <name>Luigi</name>
            <speed>
                <land>3.75</land>
                <anti-g>3.5</anti-g>
                <water>4</water>
                <air>4.25</air>
            </speed>
            <accel>3.5</accel>
            <weight>3.5</weight>
            <handling>
                <land>3.75</land>
                <anti-g>3.75</anti-g>
                <water>3.25</water>
                <air>3.75</air>
            </handling>
            <traction>3.25</traction>
            <M-turbo>3.25</M-turbo>
        </character>
        <character>
            <name>Rosalina</name>
            <speed>
                <land>4</land>
                <anti-g>3.75</anti-g>
                <water>4.25</water>
                <air>4.5</air>
            </speed>
            <accel>3.25</accel>
            <weight>3.75</weight>
            <handling>
                <land>3.25</land>
                <anti-g>3.25</anti-g>
                <water>2.75</water>
                <air>3.25</air>
            </handling>
            <traction>3.75</traction>
            <M-turbo>3.25</M-turbo>
        </character>
        <character>
            <name>Metal Mario</name>
            <speed>
                <land>4.25</land>
                <anti-g>4</anti-g>
                <water>4.5</water>
                <air>4.75</air>
            </speed>
            <accel>3.25</accel>
            <weight>4.5</weight>
            <handling>
                <land>3.25</land>
                <anti-g>3.25</anti-g>
                <water>2.75</water>
                <air>3.25</air>
            </handling>
            <traction>3.25</traction>
            <M-turbo>3</M-turbo>
        </character>
        <character>
            <name>Waluigi</name>
            <speed>
                <land>4.5</land>
                <anti-g>4.25</anti-g>
                <water>4.75</water>
                <air>5</air>
            </speed>
            <accel>3.25</accel>
            <weight>4</weight>
            <handling>
                <land>3</land>
                <anti-g>3</anti-g>
                <water>2.5</water>
                <air>3</air>
            </handling>
            <traction>3</traction>
            <M-turbo>3</M-turbo>
        </character>
        <character>
            <name>Wario</name>
            <speed>
                <land>4.75</land>
                <anti-g>4.5</anti-g>
                <water>5</water>
                <air>5.25</air>
            </speed>
            <accel>3</accel>
            <weight>4.25</weight>
            <handling>
                <land>2.75</land>
                <anti-g>2.75</anti-g>
                <water>2.25</water>
                <air>2.75</air>
            </handling>
            <traction>3.25</traction>
            <M-turbo>2.75</M-turbo>
        </character>
        <character>
            <name>Bowser</name>
            <speed>
                <land>4.75</land>
                <anti-g>4.5</anti-g>
                <water>5</water>
                <air>5.25</air>
            </speed>
            <accel>3</accel>
            <weight>4.5</weight>
            <handling>
                <land>2.5</land>
                <anti-g>2.5</anti-g>
                <water>2</water>
                <air>2.5</air>
            </handling>
            <traction>3</traction>
            <M-turbo>2.75</M-turbo>
        </character>
    </characters>
    <bodies>
        <body>
            <name>Standard Kart</name>
            <speed>
                <land>0</land>
                <anti-g>0</anti-g>
                <water>0</water>
                <air>0</air>
            </speed>
            <accel>0</accel>
            <weight>0</weight>
            <handling>
                <land>0</land>
                <anti-g>0</anti-g>
                <water>0</water>
                <air>0</air>
            </handling>
            <traction>0</traction>
            <M-turbo>0</M-turbo>
        </body>
        <body>
            <name>Pipe Frame</name>
            <speed>
                <land>-0.5</land>
